openapi: 3.0.1
info:
  description: Sample Express API in OpenAPI
  version: '1.0.0'
  title: Express API in OpenAPI
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:5000
paths:
  /posts:
    get:
      tags:
        - posts
      description: Return all posts
      summary: Get all posts
      operationId: getAllPosts
      responses:
        200:
          description: return all posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        404:
          description: Not found!
          content: {}
  /posts/{id}:
    get:
      tags:
        - get one post
      description: Return one post
      parameters:
        - name: id
          in: path
          description: Fetch a post by id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: return a post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        404:
          description: Not found!
          content: {}

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        title:
          type: string
          example: 'My name is eric'
        body:
          type: string
          example: 'My main body'
